In [1]:
import pandas as pd
from pathlib import Path

In [2]:
pd.options.display.max_rows = 999
pd.options.display.max_colwidth = 999
pd.options.display.width = 999
pd.options.display.max_columns = 999

In [3]:
demographics_path = Path().cwd().parent.joinpath('main_voter_dataset/voters_20240410_clean_with_voter_history.csv')
demographics_original = pd.read_csv(demographics_path, dtype=str)
demographics_df = demographics_original.copy()

In [12]:
def search_first_last(first_name, last_name):
    return demographics_df[(demographics_df['first_name'] == str(first_name).upper()) & (demographics_df['last_name'] == str(last_name).upper())]

In [24]:
search_first_last("Steven", "Ewing")

        Unnamed: 0 voter_registration_number ajc_id_num  status last_name first_name middle_name   county county_precinct_description residence_city municipal_precinct state_senate_district state_house_district birth_year   race gender registration_date voter_created_date last_party_voted last_vote_date general_2008 general_2010 general_2012 general_2014 general_2016 general_2018 general_2020 senate_runoff_2021 general_2022 general_runoff_2022 primary_2012 primary_2016 primary_2020 primary_2024
2008265    2008353                  03381293    6245459  Active     EWING     STEVEN        TROY   FULTON                         01H        ATLANTA                01H                   036                  059     1963.0  Black   Male        1995-09-28         10/23/1995         DEMOCRAT     01/02/2021            1            0            1            0            0            1            1                  1            0                   0            0            0            0            0
3060041    3060171                  05173449    7464763  Active     EWING     STEVEN     ANTHONY  LOWNDES                 TRAIN DEPOT         HAHIRA                NaN                   008                  175     1962.0  Other   Male        2000-10-24         10/24/2000              NaN     12/31/2020            1            1            1            1            1            1            1                  1            0                   0            0            0            0            0
3590984    3591142                  05984550    3250352  Active     EWING     STEVEN      ROBERT   FULTON                        SS16  SANDY SPRINGS               SS16                   038                  053     1959.0  Other   Male        2004-02-19         03/25/2004         Democrat     12/06/2022            1            1            1            1            1            1            1                  1            1                   1            0            1            1            0
5797873    5798159                  08860681    3894991  Active     EWING     STEVEN        PAUL  CLAYTON                   LOVEJOY 8        HAMPTON                NaN                   017                  074     1953.0  White   Male        2012-10-09         10/13/2012              NaN     10/25/2020            0            0            1            0            1            0            1                  0            0                   0            0            0            0            0