In [1]:
import pandas as pd # type: ignore
import datetime
import mariadb
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

True

In [ ]:
# need to make .env file in same folder as this script to load database connection environment variables

In [2]:
# only do this block once to get narrow_demographics.csv, then import that csv instead

sql_query = "SELECT ajc_id_num, voter_registration_number, status, county, county_precinct_description, residence_city, municipal_precinct, state_senate_district, state_house_district, birth_year, race, gender, registration_date, voter_created_date, last_party_voted, last_vote_date FROM `ga_sos_voters`.`voters_20240112_all`"

# Connect to data warehouse with MariaDB
try:
    conn = mariadb.connect(
        user=os.getenv("MARIADB_USER"),
        password=os.getenv("MARIADB_PASSWORD"),
        host=os.getenv("MARIADB_HOST"),
        port=int(os.getenv("MARIADB_PORT"))
    )
except mariadb.Error as e:
    print(f"Error connecting to MariaDB Platform: {e}")
    sys.exit(1)

# Get Cursor
cur = conn.cursor()

original_demographics_table = pd.read_sql(sql_query, conn, dtype='str')

demographics_df = original_demographics_table.copy()

demographics_df.to_csv('narrow_demographics.csv')

/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/3292727260.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  original_demographics_table = pd.read_sql(sql_query, conn, dtype='str')

In [3]:
original_demographics_df = pd.read_csv('narrow_demographics.csv', dtype='str')

In [4]:
demographics_df = original_demographics_df.copy()

In [5]:
general_2008_path = Path().cwd().parent.joinpath('output_csv/general_2008.csv')
general_2010_path = Path().cwd().parent.joinpath('output_csv/general_2010.csv')
general_2012_path = Path().cwd().parent.joinpath('output_csv/general_2012.csv')
general_2014_path = Path().cwd().parent.joinpath('output_csv/general_2014.csv')
general_2016_path = Path().cwd().parent.joinpath('output_csv/general_2016.csv')
general_2018_path = Path().cwd().parent.joinpath('output_csv/general_2018.csv')
general_2020_path = Path().cwd().parent.joinpath('output_csv/general_2020.csv')
general_2022_path = Path().cwd().parent.joinpath('output_csv/general_2022.csv')
general_runoff_2022_path = Path().cwd().parent.joinpath('output_csv/general_runoff_2022.csv')
senate_runoff_2021_path = Path().cwd().parent.joinpath('output_csv/senate_runoff_2021.csv')
primary_2012_path = Path().cwd().parent.joinpath('output_csv/primary_2012.csv')
primary_2016_path = Path().cwd().parent.joinpath('output_csv/primary_2016.csv')
primary_2020_path = Path().cwd().parent.joinpath('output_csv/primary_2020.csv')
primary_2024_path = Path().cwd().parent.joinpath('output_csv/primary_2024.csv')

In [6]:
general_2008_df = pd.read_csv(general_2008_path, dtype='str')
general_2010_df = pd.read_csv(general_2010_path, dtype='str')
general_2012_df = pd.read_csv(general_2012_path, dtype='str')
general_2014_df = pd.read_csv(general_2014_path, dtype='str')
general_2016_df = pd.read_csv(general_2016_path, dtype='str')
general_2018_df = pd.read_csv(general_2018_path, dtype='str')
general_2020_df = pd.read_csv(general_2020_path, dtype='str')
general_2022_df = pd.read_csv(general_2022_path, dtype='str')
general_runoff_2022_df = pd.read_csv(general_runoff_2022_path, dtype='str')
senate_runoff_2021_df = pd.read_csv(senate_runoff_2021_path, dtype='str')
primary_2012_df = pd.read_csv(primary_2012_path, dtype='str')
primary_2016_df = pd.read_csv(primary_2016_path, dtype='str')
primary_2020_df = pd.read_csv(primary_2020_path, dtype='str')
primary_2024_df = pd.read_csv(primary_2024_path, dtype='str')

In [7]:
general_2008_df['general_2008'] = "1"
general_2008_df_thin = general_2008_df[['voter_registration_number', 'general_2008']]
general_2010_df['general_2010'] = "1"
general_2010_df_thin = general_2010_df[['voter_registration_number', 'general_2010']]
general_2012_df['general_2012'] = "1"
general_2012_df_thin = general_2012_df[['voter_registration_number', 'general_2012']]
general_2014_df['general_2014'] = "1"
general_2014_df_thin = general_2014_df[['voter_registration_number', 'general_2014']]
general_2016_df['general_2016'] = "1"
general_2016_df_thin = general_2016_df[['voter_registration_number', 'general_2016']]
general_2018_df['general_2018'] = "1"
general_2018_df_thin = general_2018_df[['voter_registration_number', 'general_2018']]
general_2020_df['general_2020'] = "1"
general_2020_df_thin = general_2020_df[['voter_registration_number', 'general_2020']]
general_2022_df['general_2022'] = "1"
general_2022_df_thin = general_2022_df[['voter_registration_number', 'general_2022']]
general_runoff_2022_df['general_runoff_2022'] = "1"
general_runoff_2022_df_thin = general_runoff_2022_df[['voter_registration_number', 'general_runoff_2022']]
senate_runoff_2021_df['senate_runoff_2021'] = "1"
senate_runoff_2021_df_thin = senate_runoff_2021_df[['voter_registration_number', 'senate_runoff_2021']]
primary_2012_df['primary_2012'] = "1"
primary_2012_df_thin = primary_2012_df[['voter_registration_number', 'primary_2012']]
primary_2016_df['primary_2016'] = "1"
primary_2016_df_thin = primary_2016_df[['voter_registration_number', 'primary_2016']]
primary_2020_df['primary_2020'] = "1"
primary_2020_df_thin = primary_2020_df[['voter_registration_number', 'primary_2020']]
primary_2024_df['primary_2024'] = "1"
primary_2024_df_thin = primary_2024_df[['voter_registration_number', 'primary_2024']]

In [8]:
demographics_df = demographics_df.set_index('voter_registration_number').join(general_2008_df_thin.set_index('voter_registration_number'), how='outer')
demographics_df = demographics_df.join(general_2010_df_thin.set_index('voter_registration_number'), how='outer')
demographics_df = demographics_df.join(general_2012_df_thin.set_index('voter_registration_number'), how='outer')
demographics_df = demographics_df.join(general_2014_df_thin.set_index('voter_registration_number'), how='outer')
demographics_df = demographics_df.join(general_2016_df_thin.set_index('voter_registration_number'), how='outer')
demographics_df = demographics_df.join(general_2018_df_thin.set_index('voter_registration_number'), how='outer')
demographics_df = demographics_df.join(general_2020_df_thin.set_index('voter_registration_number'), how='outer')
demographics_df = demographics_df.join(senate_runoff_2021_df_thin.set_index('voter_registration_number'), how='outer')
demographics_df = demographics_df.join(general_2022_df_thin.set_index('voter_registration_number'), how='outer')
demographics_df = demographics_df.join(general_runoff_2022_df_thin.set_index('voter_registration_number'), how='outer')
demographics_df = demographics_df.join(primary_2012_df_thin.set_index('voter_registration_number'), how='outer')
demographics_df = demographics_df.join(primary_2016_df_thin.set_index('voter_registration_number'), how='outer')
demographics_df = demographics_df.join(primary_2020_df_thin.set_index('voter_registration_number'), how='outer')
demographics_df = demographics_df.join(primary_2024_df_thin.set_index('voter_registration_number'), how='outer')

In [9]:
df = demographics_df.copy()

In [10]:
df.reset_index(inplace=True)

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df.dropna(how='all', inplace=True)

In [13]:
df.pop('Unnamed: 0')

0                NaN
1             382260
2             382343
3             457294
4            7980428
              ...
11740205         NaN
11740206     9120438
11740207    11412059
11740208     9366406
11740209         NaN
Name: Unnamed: 0, Length: 11735395, dtype: object

In [14]:
df.ajc_id_num.fillna('', inplace=True)
df.status.fillna('', inplace=True)
df.county.fillna('', inplace=True)
df.residence_city.fillna('', inplace=True)
df.birth_year.fillna('', inplace=True)
df.race.fillna('', inplace=True)
df.gender.fillna('', inplace=True)
df.last_party_voted.fillna('', inplace=True)
df.last_vote_date.fillna('', inplace=True)
df.registration_date.fillna('', inplace=True)
df.voter_created_date.fillna('', inplace=True)

/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1336712094.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.ajc_id_num.fillna('', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1336712094.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.status.fillna('', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1336712094.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.county.fillna('', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1336712094.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.residence_city.fillna('', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1336712094.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.birth_year.fillna('', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1336712094.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.race.fillna('', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1336712094.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.gender.fillna('', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1336712094.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.last_party_voted.fillna('', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1336712094.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.last_vote_date.fillna('', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1336712094.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.registration_date.fillna('', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1336712094.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.voter_created_date.fillna('', inplace=True)

In [15]:
df.general_2008.fillna('0', inplace=True)
df.general_2010.fillna('0', inplace=True)
df.general_2012.fillna('0', inplace=True)
df.general_2014.fillna('0', inplace=True)
df.general_2016.fillna('0', inplace=True)
df.general_2018.fillna('0', inplace=True)
df.general_2020.fillna('0', inplace=True)
df.general_2022.fillna('0', inplace=True)
df.general_runoff_2022.fillna('0', inplace=True)
df.senate_runoff_2021.fillna('0', inplace=True)
df.primary_2012.fillna('0', inplace=True)
df.primary_2016.fillna('0', inplace=True)
df.primary_2020.fillna('0', inplace=True)
df.primary_2024.fillna('0', inplace=True)

/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1603498289.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.general_2008.fillna('0', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1603498289.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.general_2010.fillna('0', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1603498289.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.general_2012.fillna('0', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1603498289.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.general_2014.fillna('0', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1603498289.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.general_2016.fillna('0', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1603498289.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.general_2018.fillna('0', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1603498289.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.general_2020.fillna('0', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1603498289.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.general_2022.fillna('0', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1603498289.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.general_runoff_2022.fillna('0', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1603498289.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.senate_runoff_2021.fillna('0', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1603498289.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.primary_2012.fillna('0', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1603498289.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.primary_2016.fillna('0', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1603498289.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.primary_2020.fillna('0', inplace=True)
/var/folders/2d/dn3_f8x10wzf75hxkv2506g00000gp/T/ipykernel_19284/1603498289.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.primary_2024.fillna('0', inplace=True)

In [16]:
df.dropna(subset='voter_registration_number', inplace=True)

In [17]:
df

,voter_registration_number,ajc_id_num,status,county,county_precinct_description,residence_city,municipal_precinct,state_senate_district,state_house_district,birth_year,...,general_2016,general_2018,general_2020,senate_runoff_2021,general_2022,general_runoff_2022,primary_2012,primary_2016,primary_2020,primary_2024
0,00000001,,,,NaN,,NaN,NaN,NaN,,...,0,0,0,0,0,0,0,0,0,0
1,00000002,382261,Active,BANKS,ANDERSON,MAYSVILLE,6,050,032,1937.0,...,1,1,1,1,0,1,1,1,1,1
2,00000003,382344,Active,BANKS,ANDERSON,MAYSVILLE,NaN,050,032,1940.0,...,1,1,1,1,1,1,1,1,1,0
3,00000004,457295,Active,BANKS,ANDERSON,MAYSVILLE,NaN,050,032,1954.0,...,1,1,0,1,0,1,1,1,0,0
4,00000005,7980429,Cancelled,BANKS,ANDERSON,MAYSVILLE,6,050,032,1912.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11740204,87666901,,,,NaN,,NaN,NaN,NaN,,...,0,0,0,0,0,0,0,0,0,0
11740205,88837544,,,,NaN,,NaN,NaN,NaN,,...,0,0,0,0,0,0,0,0,0,0
11740206,8886827,9120439,Cancelled,FULTON,NaN,,NaN,NaN,NaN,1971.0,...,0,0,0,0,0,0,0,0,0,0
11740207,8915533,11412060,Cancelled,PAULDING,NaN,,NaN,NaN,NaN,1989.0,...,0,0,0,0,0,0,0,0,0,0
11740208,8919588,9366407,Cancelled,FLOYD,NaN,,NaN,NaN,NaN,1988.0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
df.county.value_counts()

county
FULTON        1322633
GWINNETT       880497
DEKALB         858286
COBB           839041
CHATHAM        368546
               ...
QUITMAN          3709
ECHOLS           3581
GLASCOCK         3346
WEBSTER          2769
TALIAFERRO       2405
Name: count, Length: 160, dtype: int64

In [19]:
df.to_csv('voters_20240112_all_with_voter_history_extended.csv')

In [ ]:
# uploaded csv to data warehouse using import tool after running create query to set up columns